### Write Post
POST http://localhost/api/posts/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTM0NGQ0NmMzNDVhMDAzMDZjZSIsIm5hbWUiOiJQdWJsaWMiLCJ1c2VybmFtZSI6InB1YmxpYyIsImVtYWlsIjoiam9obkBtYWlsLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W10sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODEyODQwOCwiZXhwIjoxNjA4NzMzMjA4fQ.o_5UJDzrYkalgFyzsLjxgr_ZIilO4U948iWbOTV_Bw4
Content-Type: application/json

# {
#     "title": "Hello World!",
#     "text": "I'm a cat."
# }

{
    "title": "Public",
    "text": "I'm a cat."
}

### Write Comment
POST http://localhost/api/posts/5fd930cab1f92941d88951de/comment
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDdhMzBmYjk1MWU0MTMxY2Y0YTJjYyIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBtYWlsLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6WyI1ZmQ3ZDIwNmEyNDJhYjIxODg1ZDI0OTUiXSwiZnJpZW5kc0Fza2VkIjpbXSwiaWF0IjoxNjA4MDY5MjI5LCJleHAiOjE2MDg2NzQwMjl9.FePZrAFpFjhUEhNM_ucN3_NuRIhvJ8ERTxZrj-5Pl40
Content-Type: application/json

{
    "text": "Neko"
}




### Get Posts
GET http://localhost/api/posts

### Get Posts: Author
GET http://localhost/api/posts?author=5fda15344d46c345a00306ce

### Get Posts: Registered
GET http://localhost/api/posts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTM0NGQ0NmMzNDVhMDAzMDZjZSIsIm5hbWUiOiJQdWJsaWMiLCJ1c2VybmFtZSI6InB1YmxpYyIsImVtYWlsIjoiam9obkBtYWlsLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W10sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODEyODQwOCwiZXhwIjoxNjA4NzMzMjA4fQ.o_5UJDzrYkalgFyzsLjxgr_ZIilO4U948iWbOTV_Bw4

### Get Posts: Friend
GET http://localhost/api/posts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTE1NGQ0NmMzNDVhMDAzMDZjYyIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBtYWlsLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W10sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODEyODQ3MSwiZXhwIjoxNjA4NzMzMjcxfQ.W6B8F9zU3Bsx_q-o1YGaWF56lc1MiGIq4DteVEA_eJ4

### Get Posts: Private
GET http://localhost/api/posts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTZmNGQ0NmMzNDVhMDAzMDZkMSIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJqb2huQG1haWwuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOltdLCJmcmllbmRzQXNrZWQiOltdLCJpYXQiOjE2MDgxMjg0MzMsImV4cCI6MTYwODczMzIzM30.LBQaf1K3TY38NN1X1urS20l49xEQE5Xq_pbPngOkuaA

### Get Posts: Private, Author
GET http://localhost/api/posts?author=5fda15444d46c345a00306cf
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTZmNGQ0NmMzNDVhMDAzMDZkMSIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJqb2huQG1haWwuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOltdLCJmcmllbmRzQXNrZWQiOltdLCJpYXQiOjE2MDgxMjg0MzMsImV4cCI6MTYwODczMzIzM30.LBQaf1K3TY38NN1X1urS20l49xEQE5Xq_pbPngOkuaA

### Get Posts: Private, newer
GET http://localhost/api/posts?newer=2020-12-16T14:25:51.722Z
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTZmNGQ0NmMzNDVhMDAzMDZkMSIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJqb2huQG1haWwuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOltdLCJmcmllbmRzQXNrZWQiOltdLCJpYXQiOjE2MDgxMjg0MzMsImV4cCI6MTYwODczMzIzM30.LBQaf1K3TY38NN1X1urS20l49xEQE5Xq_pbPngOkuaA

### Get Posts: Private, older
GET http://localhost/api/posts?older=2020-12-16T14:25:51.722Z
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTZmNGQ0NmMzNDVhMDAzMDZkMSIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJqb2huQG1haWwuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOltdLCJmcmllbmRzQXNrZWQiOltdLCJpYXQiOjE2MDgxMjg0MzMsImV4cCI6MTYwODczMzIzM30.LBQaf1K3TY38NN1X1urS20l49xEQE5Xq_pbPngOkuaA

### Get Posts: Private, max
GET http://localhost/api/posts?max=1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTZmNGQ0NmMzNDVhMDAzMDZkMSIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJqb2huQG1haWwuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOltdLCJmcmllbmRzQXNrZWQiOltdLCJpYXQiOjE2MDgxMjg0MzMsImV4cCI6MTYwODczMzIzM30.LBQaf1K3TY38NN1X1urS20l49xEQE5Xq_pbPngOkuaA




### Get Post: Public
GET http://localhost/api/posts/5fda190e4d46c345a00306d5

### Get Post: Registered
GET http://localhost/api/posts/5fda18ef4d46c345a00306d4
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTE1NGQ0NmMzNDVhMDAzMDZjYyIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBtYWlsLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W10sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODEyODQ3MSwiZXhwIjoxNjA4NzMzMjcxfQ.W6B8F9zU3Bsx_q-o1YGaWF56lc1MiGIq4DteVEA_eJ4

### Get Post: Registered Fail
GET http://localhost/api/posts/5fda18ef4d46c345a00306d4

### Get Post: Friend
GET http://localhost/api/posts/5fda18de4d46c345a00306d3
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTE1NGQ0NmMzNDVhMDAzMDZjYyIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBtYWlsLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W10sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODEyODQ3MSwiZXhwIjoxNjA4NzMzMjcxfQ.W6B8F9zU3Bsx_q-o1YGaWF56lc1MiGIq4DteVEA_eJ4

### Get Post: Friend Fail
GET http://localhost/api/posts/5fda18de4d46c345a00306d3
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTZmNGQ0NmMzNDVhMDAzMDZkMSIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJqb2huQG1haWwuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOltdLCJmcmllbmRzQXNrZWQiOltdLCJpYXQiOjE2MDgxMjg0MzMsImV4cCI6MTYwODczMzIzM30.LBQaf1K3TY38NN1X1urS20l49xEQE5Xq_pbPngOkuaA

### Get Post: Private
GET http://localhost/api/posts/5fda18c24d46c345a00306d2
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTZmNGQ0NmMzNDVhMDAzMDZkMSIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJqb2huQG1haWwuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOltdLCJmcmllbmRzQXNrZWQiOltdLCJpYXQiOjE2MDgxMjg0MzMsImV4cCI6MTYwODczMzIzM30.LBQaf1K3TY38NN1X1urS20l49xEQE5Xq_pbPngOkuaA

### Get Post: Private Fail
GET http://localhost/api/posts/5fda18c24d46c345a00306d2
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGExNTE1NGQ0NmMzNDVhMDAzMDZjYyIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBtYWlsLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W10sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODEyODQ3MSwiZXhwIjoxNjA4NzMzMjcxfQ.W6B8F9zU3Bsx_q-o1YGaWF56lc1MiGIq4DteVEA_eJ4
