### Write Post
POST http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts/
#POST http://localhost/api/posts/
Authorization: JWT 
Content-Type: application/json

# {
#     "title": "Hello World!",
#     "text": "I'm a cat."
# }

{
    "title": "Public",
    "text": "I'm a cat."
}

### Write Comment
POST http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts/5fd930cab1f92941d88951de/comment
#POST http://localhost/api/posts/5fd930cab1f92941d88951de/comment
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkB1c2VyLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W3siX2lkIjoiNWZkZWVkMDMwMGM0OGIwMDFhOTEzZTEzIiwidXNlcm5hbWUiOiJwcml2YXRlIn0seyJfaWQiOiI1ZmRlZWJmYzAwYzQ4YjAwMWE5MTNlMTEiLCJ1c2VybmFtZSI6ImZyaWVuZHMifV0sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODQ0NzEwMCwiZXhwIjoxNjA5MDUxOTAwfQ.TLzK_33vYGrZCbF-ORD9Aowi3XqrqEzjbjLpWS9rrtc 
Content-Type: application/json

{
    "text": "Neko"
}




### Get Posts
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts
#GET http://localhost/api/posts

### Get Posts: Author
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts?author=5fdeed5900c48b001a913e15
#GET http://localhost/api/posts?author=5fda15344d46c345a00306ce

### Get Posts: Registered
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts
#GET http://localhost/api/posts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlODE4ZGQ1Y2Q2MDAxYWNiMzA1YiIsIm5hbWUiOiJSZWdpc3RlcmVkIiwidXNlcm5hbWUiOiJyZWdpc3RlcmVkIiwiZW1haWwiOiJyZWdpc3RlcmRAdXNlci5kZSIsInByaXZhY3kiOiJyZWdpc3RlcmVkIiwiZnJpZW5kcyI6W10sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODQ0NzM0MSwiZXhwIjoxNjA5MDUyMTQxfQ.D6Bq99ofS8XiiZXcIQhT3Ax2v8OCTlJBulkdjKVh4sw 

### Get Posts: Friend
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts
#GET http://localhost/api/posts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkB1c2VyLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W3siX2lkIjoiNWZkZWVkMDMwMGM0OGIwMDFhOTEzZTEzIiwidXNlcm5hbWUiOiJwcml2YXRlIn0seyJfaWQiOiI1ZmRlZWJmYzAwYzQ4YjAwMWE5MTNlMTEiLCJ1c2VybmFtZSI6ImZyaWVuZHMifV0sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODQ0NzEwMCwiZXhwIjoxNjA5MDUxOTAwfQ.TLzK_33vYGrZCbF-ORD9Aowi3XqrqEzjbjLpWS9rrtc 

### Get Posts: Private
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts
#GET http://localhost/api/posts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDAzMDBjNDhiMDAxYTkxM2UxMyIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJwcml2YXRlQHVzZXIuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOlt7Il9pZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsInVzZXJuYW1lIjoiam9obiJ9XSwiZnJpZW5kc0Fza2VkIjpbXSwiaWF0IjoxNjA4NDQ3MjkxLCJleHAiOjE2MDkwNTIwOTF9.0GT52UZh1_f6UH_yFT5ntLgxgGhHhVh5hAI8EIKIIvI 

### Get Posts: Private, Author
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts?author=5fdeed0300c48b001a913e13
#GET http://localhost/api/posts?author=5fda15444d46c345a00306cf
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDAzMDBjNDhiMDAxYTkxM2UxMyIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJwcml2YXRlQHVzZXIuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOlt7Il9pZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsInVzZXJuYW1lIjoiam9obiJ9XSwiZnJpZW5kc0Fza2VkIjpbXSwiaWF0IjoxNjA4NDQ3MjkxLCJleHAiOjE2MDkwNTIwOTF9.0GT52UZh1_f6UH_yFT5ntLgxgGhHhVh5hAI8EIKIIvI 

### Get Posts: Private, newer
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts?newer=2020-12-20T05:59:33.465Z
#GET http://localhost/api/posts?newer=2020-12-16T14:25:51.722Z
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDAzMDBjNDhiMDAxYTkxM2UxMyIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJwcml2YXRlQHVzZXIuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOlt7Il9pZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsInVzZXJuYW1lIjoiam9obiJ9XSwiZnJpZW5kc0Fza2VkIjpbXSwiaWF0IjoxNjA4NDQ3MjkxLCJleHAiOjE2MDkwNTIwOTF9.0GT52UZh1_f6UH_yFT5ntLgxgGhHhVh5hAI8EIKIIvI 

### Get Posts: Private, older
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts?older=2020-12-20T05:59:33.465Z
#GET http://localhost/api/posts?older=2020-12-16T14:25:51.722Z
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDAzMDBjNDhiMDAxYTkxM2UxMyIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJwcml2YXRlQHVzZXIuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOlt7Il9pZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsInVzZXJuYW1lIjoiam9obiJ9XSwiZnJpZW5kc0Fza2VkIjpbXSwiaWF0IjoxNjA4NDQ3MjkxLCJleHAiOjE2MDkwNTIwOTF9.0GT52UZh1_f6UH_yFT5ntLgxgGhHhVh5hAI8EIKIIvI 

### Get Posts: Private, max
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts?max=1
#GET http://localhost/api/posts?max=1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDAzMDBjNDhiMDAxYTkxM2UxMyIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJwcml2YXRlQHVzZXIuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOlt7Il9pZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsInVzZXJuYW1lIjoiam9obiJ9XSwiZnJpZW5kc0Fza2VkIjpbXSwiaWF0IjoxNjA4NDQ3MjkxLCJleHAiOjE2MDkwNTIwOTF9.0GT52UZh1_f6UH_yFT5ntLgxgGhHhVh5hAI8EIKIIvI 




### Get Post: Public
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts/5fdee7f2dd5cd6001acb305a
#GET http://localhost/api/posts/5fdd2488d153c307fc6e598f

### Get Post: Registered
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts/5fdee845dd5cd6001acb305c
#GET http://localhost/api/posts/5fda18ef4d46c345a00306d4
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkB1c2VyLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W3siX2lkIjoiNWZkZWVkMDMwMGM0OGIwMDFhOTEzZTEzIiwidXNlcm5hbWUiOiJwcml2YXRlIn0seyJfaWQiOiI1ZmRlZWJmYzAwYzQ4YjAwMWE5MTNlMTEiLCJ1c2VybmFtZSI6ImZyaWVuZHMifV0sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODQ0NzEwMCwiZXhwIjoxNjA5MDUxOTAwfQ.TLzK_33vYGrZCbF-ORD9Aowi3XqrqEzjbjLpWS9rrtc 

### Get Post: Registered Fail
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts/5fdee845dd5cd6001acb305c
#GET http://localhost/api/posts/5fda18ef4d46c345a00306d4

### Get Post: Friend
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts/5fdeec3a00c48b001a913e12
#GET http://localhost/api/posts/5fda18de4d46c345a00306d3
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkB1c2VyLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W3siX2lkIjoiNWZkZWVkMDMwMGM0OGIwMDFhOTEzZTEzIiwidXNlcm5hbWUiOiJwcml2YXRlIn0seyJfaWQiOiI1ZmRlZWJmYzAwYzQ4YjAwMWE5MTNlMTEiLCJ1c2VybmFtZSI6ImZyaWVuZHMifV0sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODQ0NzEwMCwiZXhwIjoxNjA5MDUxOTAwfQ.TLzK_33vYGrZCbF-ORD9Aowi3XqrqEzjbjLpWS9rrtc 

### Get Post: Friend Fail
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts/5fdeec3a00c48b001a913e12
#GET http://localhost/api/posts/5fda18de4d46c345a00306d3
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDAzMDBjNDhiMDAxYTkxM2UxMyIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJwcml2YXRlQHVzZXIuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOlt7Il9pZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsInVzZXJuYW1lIjoiam9obiJ9XSwiZnJpZW5kc0Fza2VkIjpbXSwiaWF0IjoxNjA4NDQ3MjkxLCJleHAiOjE2MDkwNTIwOTF9.0GT52UZh1_f6UH_yFT5ntLgxgGhHhVh5hAI8EIKIIvI 

### Get Post: Private
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts/5fdeed2900c48b001a913e14
#GET http://localhost/api/posts/5fda18c24d46c345a00306d2
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDAzMDBjNDhiMDAxYTkxM2UxMyIsIm5hbWUiOiJQcml2YXRlIiwidXNlcm5hbWUiOiJwcml2YXRlIiwiZW1haWwiOiJwcml2YXRlQHVzZXIuZGUiLCJwcml2YWN5IjoicHJpdmF0ZSIsImZyaWVuZHMiOlt7Il9pZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsInVzZXJuYW1lIjoiam9obiJ9XSwiZnJpZW5kc0Fza2VkIjpbXSwiaWF0IjoxNjA4NDQ3MjkxLCJleHAiOjE2MDkwNTIwOTF9.0GT52UZh1_f6UH_yFT5ntLgxgGhHhVh5hAI8EIKIIvI 

### Get Post: Private Fail
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts/5fdeed2900c48b001a913e14
#GET http://localhost/api/posts/5fda18c24d46c345a00306d2
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkB1c2VyLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W3siX2lkIjoiNWZkZWVkMDMwMGM0OGIwMDFhOTEzZTEzIiwidXNlcm5hbWUiOiJwcml2YXRlIn0seyJfaWQiOiI1ZmRlZWJmYzAwYzQ4YjAwMWE5MTNlMTEiLCJ1c2VybmFtZSI6ImZyaWVuZHMifV0sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODQ0NzEwMCwiZXhwIjoxNjA5MDUxOTAwfQ.TLzK_33vYGrZCbF-ORD9Aowi3XqrqEzjbjLpWS9rrtc 

### Get Post: Only Comments
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/posts/5fdeed7d00c48b001a913e16?onlyComments=true
#GET http://localhost/api/posts/5fda190e4d46c345a00306d5?onlyComments=true