### Create
POST http://localhost/api/users/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@mail.de",
    "username": "john",
    "password": "123456"
}

### Authentification
POST http://localhost/api/users/authenticate
Content-Type: application/json

{
    "username": "john",
    "password": "123456"
}

### Authentification; Fail
POST http://localhost/api/users/authenticate
Content-Type: application/json

{
    "username": "john",
    "password": "12345"
}

### Profile
GET http://localhost/api/users/5fd7a30fb951e4131cf4a2cc
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDdhMzBmYjk1MWU0MTMxY2Y0YTJjYyIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBtYWlsLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W10sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwNzk2OTM0MSwiZXhwIjoxNjA4NTc0MTQxfQ.O7_aROwo-frXKuFbuJdovmbmj8m0xVwD5Pl9wp8eg8o

### Change User
POST http://localhost/api/users/5fd95f8eb4599529f8194500
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDk1ZjhlYjQ1OTk1MjlmODE5NDUwMCIsIm5hbWUiOiJNaWF1IiwidXNlcm5hbWUiOiJNaWF1IiwiZW1haWwiOiJqb2huQG1haWwuZGUiLCJwcml2YWN5IjoiZXZlcnlvbmUiLCJmcmllbmRzIjpbXSwiZnJpZW5kc0Fza2VkIjpbXSwiaWF0IjoxNjA4MDgxMzI3LCJleHAiOjE2MDg2ODYxMjd9.WUMhAZKKCPpg7lo_VS94Dp2vQBizJZelZfHuWAwPPdM
Content-Type: application/json

{
    "username": "changed2",
    "password": "12345678",
    "privacy": "private"
}

### Change User; Fail
POST http://localhost/api/users/5fd95f8eb4599529f8194500
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDdhMzBmYjk1MWU0MTMxY2Y0YTJjYyIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBtYWlsLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W10sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwNzk2OTM0MSwiZXhwIjoxNjA4NTc0MTQxfQ.O7_aROwo-frXKuFbuJdovmbmj8m0xVwD5Pl9wp8eg8o
Content-Type: application/json

{
    "username": "changed",
    "password": "12345678",
    "privacy": "private"
}

### Profile; Fail
GET http://localhost/api/users/5fd7a30fb951e4131cf4a2cd

### Friend; self
POST http://localhost/api/users/5fd7a30fb951e4131cf4a2cc/askFriend
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDdhMzBmYjk1MWU0MTMxY2Y0YTJjYyIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBtYWlsLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W10sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwNzk2OTM0MSwiZXhwIjoxNjA4NTc0MTQxfQ.O7_aROwo-frXKuFbuJdovmbmj8m0xVwD5Pl9wp8eg8o

### Friend; ask
POST http://localhost/api/users/5fd7d206a242ab21885d2495/askFriend
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDdhMzBmYjk1MWU0MTMxY2Y0YTJjYyIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBtYWlsLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W10sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwNzk2OTM0MSwiZXhwIjoxNjA4NTc0MTQxfQ.O7_aROwo-frXKuFbuJdovmbmj8m0xVwD5Pl9wp8eg8o

### Friend; both
POST http://localhost/api/users/5fd7a30fb951e4131cf4a2cc/askFriend
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDdkMjA2YTI0MmFiMjE4ODVkMjQ5NSIsIm5hbWUiOiJ0ZXN0IiwidXNlcm5hbWUiOiJ0MDEiLCJlbWFpbCI6ImpvaG5AbWFpbC5kZSIsInByaXZhY3kiOiJldmVyeW9uZSIsImZyaWVuZHMiOltdLCJmcmllbmRzQXNrZWQiOlsiNWZkN2EzMGZiOTUxZTQxMzFjZjRhMmNjIl0sImlhdCI6MTYwNzk3OTkxNiwiZXhwIjoxNjA4NTg0NzE2fQ.zQ_g6q9mtkbq3Lj0OH374Dn217Drw-VYkhCye1qnhnw
