### Create
POST http://course-project-v1-finishedprojects.rahtiapp.fi/api/users/register
#POST http://localhost/api/users/register
Content-Type: application/json

{
    "name": "Private",
    "email": "john@mail.de",
    "username": "private",
    "password": "123456"
}

### Authentification
POST http://course-project-v1-finishedprojects.rahtiapp.fi/api/users/authenticate
#POST http://localhost/api/users/authenticate
Content-Type: application/json

{
    "username": "john",
    "password": "123456"
}

### Authentification; Fail
POST http://course-project-v1-finishedprojects.rahtiapp.fi/api/users/authenticate
#POST http://localhost/api/users/authenticate
Content-Type: application/json

{
    "username": "private",
    "password": "12345"
}

### Profile
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/users/5fda15614d46c345a00306d0
#GET http://localhost/api/users/5fda15614d46c345a00306d0
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkB1c2VyLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W3siX2lkIjoiNWZkZWVkMDMwMGM0OGIwMDFhOTEzZTEzIiwidXNlcm5hbWUiOiJwcml2YXRlIn0seyJfaWQiOiI1ZmRlZWJmYzAwYzQ4YjAwMWE5MTNlMTEiLCJ1c2VybmFtZSI6ImZyaWVuZHMifV0sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODQ0NzEwMCwiZXhwIjoxNjA5MDUxOTAwfQ.TLzK_33vYGrZCbF-ORD9Aowi3XqrqEzjbjLpWS9rrtc 

### Profile; Fail
GET http://course-project-v1-finishedprojects.rahtiapp.fi/api/users/5fd7a30fb951e4131cf4a2cd
#GET http://localhost/api/users/5fd7a30fb951e4131cf4a2cd

### Change User
POST http://course-project-v1-finishedprojects.rahtiapp.fi/api/users/5fda15444d46c345a00306cf
#POST http://localhost/api/users/5fda15444d46c345a00306cf
Authorization: JWT 
Content-Type: application/json

{
    "username": "changed2",
    "password": "12345678",
    "privacy": "private"
}

### Change User; Fail
POST http://course-project-v1-finishedprojects.rahtiapp.fi/api/users/5fd95f8eb4599529f8194500
#POST http://localhost/api/users/5fd95f8eb4599529f8194500
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkB1c2VyLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W3siX2lkIjoiNWZkZWVkMDMwMGM0OGIwMDFhOTEzZTEzIiwidXNlcm5hbWUiOiJwcml2YXRlIn0seyJfaWQiOiI1ZmRlZWJmYzAwYzQ4YjAwMWE5MTNlMTEiLCJ1c2VybmFtZSI6ImZyaWVuZHMifV0sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODQ0NzEwMCwiZXhwIjoxNjA5MDUxOTAwfQ.TLzK_33vYGrZCbF-ORD9Aowi3XqrqEzjbjLpWS9rrtc 

{
    "username": "changed",
    "password": "12345678",
    "privacy": "private"
}

### Friend; self
POST http://course-project-v1-finishedprojects.rahtiapp.fi/api/users/5fd7a30fb951e4131cf4a2cc/askFriend
#POST http://localhost/api/users/5fd7a30fb951e4131cf4a2cc/askFriend
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkB1c2VyLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W3siX2lkIjoiNWZkZWVkMDMwMGM0OGIwMDFhOTEzZTEzIiwidXNlcm5hbWUiOiJwcml2YXRlIn0seyJfaWQiOiI1ZmRlZWJmYzAwYzQ4YjAwMWE5MTNlMTEiLCJ1c2VybmFtZSI6ImZyaWVuZHMifV0sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODQ0NzEwMCwiZXhwIjoxNjA5MDUxOTAwfQ.TLzK_33vYGrZCbF-ORD9Aowi3XqrqEzjbjLpWS9rrtc 

### Friend; ask
POST http://course-project-v1-finishedprojects.rahtiapp.fi/api/users/5fda15154d46c345a00306cc/askFriend
#POST http://localhost/api/users/5fda15154d46c345a00306cc/askFriend
Authorization: JWT 

### Friend; both
POST http://course-project-v1-finishedprojects.rahtiapp.fi/api/users/5fd7a30fb951e4131cf4a2cc/askFriend
#POST http://localhost/api/users/5fd7a30fb951e4131cf4a2cc/askFriend
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGVlZDU5MDBjNDhiMDAxYTkxM2UxNSIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkB1c2VyLmRlIiwicHJpdmFjeSI6ImV2ZXJ5b25lIiwiZnJpZW5kcyI6W3siX2lkIjoiNWZkZWVkMDMwMGM0OGIwMDFhOTEzZTEzIiwidXNlcm5hbWUiOiJwcml2YXRlIn0seyJfaWQiOiI1ZmRlZWJmYzAwYzQ4YjAwMWE5MTNlMTEiLCJ1c2VybmFtZSI6ImZyaWVuZHMifV0sImZyaWVuZHNBc2tlZCI6W10sImlhdCI6MTYwODQ0NzEwMCwiZXhwIjoxNjA5MDUxOTAwfQ.TLzK_33vYGrZCbF-ORD9Aowi3XqrqEzjbjLpWS9rrtc 
